version: '3'
services:

  wordpress:
#    image: wordpress:${WORDPRESS_TAG:?err} This is the official docker image. Instead, we're using the dockerfile that adds additional php extensions for our project, such as redis.
    build:
      context: ./docker
      dockerfile: ./docker/local.dockerfile
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/wordpress.ini
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:?err}
      WORDPRESS_DB_USER: ${MYSQL_USER:?err}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:?err}
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: always

  mysql:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
      MYSQL_USER: ${MYSQL_USER:?err}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?err}
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./html:/var/www/html
    ports:
      - ${WORDPRESS_HTTP_PORT:?err}:80
    links:
      - wordpress
    depends_on:
      - wordpress
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - ./redis:/data
    restart: always
     

#  phpmyadmin:
#    image: phpmyadmin
#    restart: always
#    ports:
#      - ${PHPMYADMIN_PORT:?err}:80
#    environment:
#      - PMA_ARBITRARY=1
#      - UPLOAD_LIMIT=500M
#      - PMA_HOST=mysql
#      - PMA_PORT=3306
#    links:
#      - mysql
